server:
  port: 8082

spring:
  profiles:
    active: qa

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: Sprint-Boot-Initial
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hello To My App

---

spring:
  config:
    activate:
      on-profile: qa
  application:
    name: Sprint-Boot-Initial
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hello To My App

---

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: Sprint-Boot-Initial
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hello To My App
